---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsvp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rsvp
    spec:
      containers:
        -
          env:
            -
              name: MONGODB_HOST
              value: mongodb
            -
              name: LINK
              value: "http://www.meetup.com/Google-Cloud-Developer-Community-Mumbai/"
            -
              name: TEXT1
              value: GoogleCloud
            -
              name: TEXT2
              value: "Developer Community"
            -
              name: LOGO
              value: "https://secure.meetupstatic.com/photos/member/b/3/1/2/member_278865842.jpeg"
            -
              name: COMPANY
              value: "ABC Pvt. Ltd."
          image: teamcloudyuga/rsvpapp
          name: rsvp-app
          ports:
            -
              containerPort: 5000
              name: web-port