apiVersion: v1
kind: ReplicationController
metadata:
  name: red
spec:
  replicas: 3
  template:
    metadata:
      labels:
        color: red
    spec:
      containers:
      - image: janakiramm/color
        name: red
        env:
          - name: "COLOR"
            value: "red"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: green
spec:
  replicas: 3
  template:
    metadata:
      labels:
        color: green
    spec:
      containers:
      - image: janakiramm/color
        name: green
        env:
          - name: "COLOR"
            value: "green"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: yellow
spec:
  replicas: 3
  template:
    metadata:
      labels:
        color: yellow
    spec:
      containers:
      - image: janakiramm/color
        name: yellow
        env:
          - name: "COLOR"
            value: "yellow"
        ports:
        - containerPort: 80